#!/bin/sh

WIFI=$(cat /sys/class/net/w*/operstate 2>/dev/null)
SSID=$(nmcli -t -f active,ssid dev wifi | grep -E '^yes' | cut -d\' -f2 | awk -F: '{ print $2 }')

case "$WIFI" in
  up) echo "  $SSID" ;;
  down) echo " No Wifi" ;;
esac
