#!/bin/sh

for battery in /sys/class/power_supply/BAT?*; do
  case "$(cat "$battery/status" 2>&1)" in
    "Full")         status="  " ;;
    "Discharging")  status="  " ;;
    "Charging")     status="  " ;;
    "Not charging") status="  " ;;
    "Unknown")      status="  " ;;
    *) exit 1 ;;
  esac
  capacity="$(cat "$battery/capacity" 2>&1)"
  printf "%s%d%%\n" "$status" "$capacity"
done && printf "\\n"
