#!/bin/sh

for battery in /sys/class/power_supply/BAT?*; do
  case "$(cat "$battery/status" 2>&1)" in
    "Full") status="  " ;;
    "Discharging")
      if [ "$(cat "$battery/capacity")" -gt 75 ]; then
        status="  "
      elif [ "$(cat "$battery/capacity")" -gt 50 ]; then
        status="  "
      elif [ "$(cat "$battery/capacity")" -gt 25 ]; then
        status="  "
      elif [ "$(cat "$battery/capacity")" -gt 10 ]; then
        status="  "
      elif [ "$(cat "$battery/capacity")" -gt 0 ]; then
        status="  "
        fi ;;
    "Charging") status="  " ;;
    "Not charging") status="  " ;;
    "Unknown") status="  " ;;
    *) exit 1 ;;
  esac
  capacity="$(cat "$battery/capacity" 2>&1)"
  printf "%s%d%%\n" "$status" "$capacity"
done && printf "\\n"
