#!/bin/sh

mute=$(pulsemixer --get-mute)
vol=$(pulsemixer --get-volume | awk {'print $1'})

if [ "$mute" = "1" ]; then
  echo " Muted"
elif [ "$(echo "$vol" | tr -d "%")" -gt 65 ]; then
  echo "  $vol%"
elif [ "$(echo "$vol" | tr -d "%")" -gt 25 ]; then
  echo "  $vol%"
else
  echo "  $vol%"
fi
