#!/bin/sh

MUTE=$(pulsemixer --get-mute)
VOL=$(pulsemixer --get-volume | awk '{ print $1 }')

if [ "$MUTE" = "1" ]; then
  echo " Muted"
elif [ "$(echo "$VOL" | tr -d "%")" -gt 65 ]; then
  echo "  $VOL%"
elif [ "$(echo "$VOL" | tr -d "%")" -gt 25 ]; then
  echo "  $VOL%"
else
  echo "  $VOL%"
fi
