#!/bin/sh

DOAS=/usr/bin/doas

help_menu(){
  cat << halp

  Help Menu

  Usage: ./setup [command]

  Commands:
  install       install dotfiles
  remove        remove dotfiles
  aur           install paru
  -h|--h|help   displays this menu

  Running this script without a command will display
  a menu and allow you to select an option.

halp
}

check_stow(){
  if [[ -f /bin/stow ]]; then
    return
  else
    clear
    echo "You need to install 'stow' to use this script. Install? (y/n)"; read -r a;
    case $a in
      y)
        if [ -x "$DOAS" ]; then
          echo "using doas"
          doas pacman -Sy stow
        elif [ ! -x "$DOAS" ]; then
          echo "using sudo"
          sudo pacman -Sy stow
        fi
        ;;
      n) exit 0
        ;;
      *) check_stow
        ;;
    esac
  fi
}
check_stow

install_dots(){
  stow alacritty &
  stow bash &
  stow bat &
  stow bin &
  stow config &
  stow lf &
  stow mako &
  stow neofetch &
  stow nvim &
  stow river &
  stow share &
  stow sway &
  stow waybar &
  stow wofi &
  echo "dotfiles installed"
}

remove_dots(){
  stow -D alacritty &
  stow -D bash &
  stow -D bat &
  stow -D bin &
  stow -D config &
  stow -D lf &
  stow -D mako &
  stow -D neofetch &
  stow -D nvim &
  stow -D river &
  stow -D share &
  stow -D sway &
  stow -D waybar &
  stow -D wofi &
  echo "dotfiles removed"
}

check_git(){
  if [[ -f /bin/git ]]; then
    return
  else
    clear
    echo "You need to install 'git' to use this script. Install? (y/n)"; read -r a;
    case $a in
      y)
        if [ -x "$DOAS" ]; then
          echo "using doas"
          doas pacman -Sy git
        elif [ ! -x "$DOAS" ]; then
          echo "using sudo"
          sudo pacman -Sy git
        fi
        ;;
      n) exit 0
        ;;
      *) check_git
        ;;
    esac
  fi
}

install_paru(){
  check_git
  if [[ -d ./paru ]]; then
    printf "\nparu is already installed\n"
  else
    if [ -x "$DOAS" ]; then
      echo "using doas"
      doas pacman -Sy --needed base-devel
    elif [ ! -x "$DOAS" ]; then
      echo "using sudo"
      sudo pacman -Sy --needed base-devel
    fi
    git clone https://aur.archlinux.org/paru.git
    cd paru
    makepkg -si
  fi
}

menu(){
  cat << options

  Welcome to Derek's Dotfiles!

  Please select an option:

  1) install dots
  2) remove dots
  3) install aur (paru)

  Ctrl-c to quit

options

  read -r answer;

  case $answer in

    1) install_dots
      ;;

    2) remove_dots
      ;;

    3) install_paru
      ;;

    *) echo "not an option...aborting!"
      ;;

    esac
  }

case $1 in
  install)
    install_dots
    ;;
  remove)
    remove_dots
    ;;
  aur)
    install_paru
    ;;
  -h|--h|help)
    help_menu
    ;;
  *)
    menu
    ;;
esac
